name: CI

on: [push, pull_request]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.dotnet.name }}
    runs-on: ${{ matrix.platform.os }}
    
    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: MacOS, os: macos-14, rid: osx-x64 }
        - { name: Windows VS2022, os: windows-2022, rid: win-x64 }
        dotnet:
        - { name: .NET 8, version: '8.0.x' }

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET ${{ matrix.dotnet.version }} SDK
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet.version }}
      - name: Enforce SDK Version
        run: dotnet new globaljson --sdk-version ${{ steps.setup-dotnet.outputs.dotnet-version }} --force
      - name: Verify SDK Installation
        run: dotnet --info
      - name: Install Dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Publish
        run: dotnet publish --runtime ${{ matrix.platform.rid }} --self-contained --configuration Release -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clockify-${{ matrix.platform.os }}
          path: bin/Publish/dev.duerrenberger.clockify.sdPlugin
  package:
    name: Package Builds
    runs-on: macos-14
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Clean Up Artifacts
        shell: bash
        run: |
          mkdir $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin
          mkdir $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/Windows
          mkdir $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/macOS
          mv $GITHUB_WORKSPACE/clockify-windows-2022/* $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/Windows/
          mv $GITHUB_WORKSPACE/clockify-macos-14/* $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/macOS/
          mv $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/Windows/Images/ $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/
          mv $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/Windows/PropertyInspector/ $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/
          mv $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/Windows/manifest.json $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/
          rm -r $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/macOS/Images
          rm -r $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/macOS/PropertyInspector
          rm $GITHUB_WORKSPACE/dev.duerrenberger.clockify.sdPlugin/macOS/manifest.json
          mkdir $GITHUB_WORKSPACE/publish
      - name: Build StreamDeck App
        uses: SantiMA10/streamdeck-action@v0.0.2
        with:
          input-directory: "/dev.duerrenberger.clockify.sdPlugin"
          output-directory: "/publish"
      - name: Upload StreamDeck App
        uses: actions/upload-artifact@v4
        with:
          name: dev.duerrenberger.clockify.streamDeckPlugin
          path: publish/dev.duerrenberger.clockify.streamDeckPlugin
